<?php

return [
    /*
    |--------------------------------------------------------------------------
    | System Permissions
    |--------------------------------------------------------------------------
    |
    | Define all system-wide permissions here.
    | Format: {module}.{resource}.{action}
    |
    */

    'permissions' => [
        // Core module permissions
        'core.users.view',
        'core.users.viewAny',
        'core.users.create',
        'core.users.update',
        'core.users.delete',
        'core.users.restore',

        'core.roles.view',
        'core.roles.viewAny',
        'core.roles.create',
        'core.roles.update',
        'core.roles.delete',
        'core.roles.restore',

        'core.permissions.view',
        'core.permissions.viewAny',

        'core.teams.view',
        'core.teams.viewAny',
        'core.teams.create',
        'core.teams.update',
        'core.teams.delete',
        'core.teams.restore',

        'core.custom_fields.view',
        'core.custom_fields.viewAny',
        'core.custom_fields.create',
        'core.custom_fields.update',
        'core.custom_fields.delete',
        'core.custom_fields.restore',

        'core.tenants.view',
        'core.tenants.viewAny',
        'core.tenants.create',
        'core.tenants.update',
        'core.tenants.delete',
        'core.tenants.restore',

        'core.audit_logs.view',
        'core.audit_logs.viewAny',
        'core.audit_logs.delete',

        'platform.manage',

        // CRM module permissions (for future use)
        'crm.leads.view',
        'crm.leads.viewAny',
        'crm.leads.create',
        'crm.leads.update',
        'crm.leads.delete',
        'crm.leads.restore',

        'crm.contacts.view',
        'crm.contacts.viewAny',
        'crm.contacts.create',
        'crm.contacts.update',
        'crm.contacts.delete',
        'crm.contacts.restore',

        'crm.deals.view',
        'crm.deals.viewAny',
        'crm.deals.create',
        'crm.deals.update',
        'crm.deals.delete',
        'crm.deals.restore',

        'crm.accounts.view',
        'crm.accounts.viewAny',
        'crm.accounts.create',
        'crm.accounts.update',
        'crm.accounts.delete',
        'crm.accounts.restore',

        'crm.pipelines.view',
        'crm.pipelines.viewAny',
        'crm.pipelines.create',
        'crm.pipelines.update',
        'crm.pipelines.delete',
        'crm.pipelines.restore',

        'crm.reports.view',
        'crm.reports.viewAny',

        'crm.workflows.view',
        'crm.workflows.viewAny',
        'crm.workflows.create',
        'crm.workflows.update',
        'crm.workflows.delete',
        'crm.workflows.restore',

        'crm.import.view',
        'crm.import.viewAny',
        'crm.import.create',
        'crm.import.update',
        'crm.import.delete',

        'crm.export.view',
        'crm.export.viewAny',
        'crm.export.create',
        'crm.export.update',
        'crm.export.delete',

        'crm.email_accounts.view',
        'crm.email_accounts.viewAny',
        'crm.email_accounts.create',
        'crm.email_accounts.update',
        'crm.email_accounts.delete',
        'crm.email_accounts.restore',

        'crm.email_templates.view',
        'crm.email_templates.viewAny',
        'crm.email_templates.create',
        'crm.email_templates.update',
        'crm.email_templates.delete',
        'crm.email_templates.restore',

        'crm.email_campaigns.view',
        'crm.email_campaigns.viewAny',
        'crm.email_campaigns.create',
        'crm.email_campaigns.update',
        'crm.email_campaigns.delete',
        'crm.email_campaigns.restore',

        'crm.calendar_integrations.view',
        'crm.calendar_integrations.viewAny',
        'crm.calendar_integrations.create',
        'crm.calendar_integrations.update',
        'crm.calendar_integrations.delete',

        'crm.lead_assignment_rules.view',
        'crm.lead_assignment_rules.viewAny',
        'crm.lead_assignment_rules.create',
        'crm.lead_assignment_rules.update',
        'crm.lead_assignment_rules.delete',
        'crm.lead_assignment_rules.restore',

        // ERP module permissions
        'erp.core.view',
        'erp.core.manage',

        'erp.products.view',
        'erp.products.viewAny',
        'erp.products.create',
        'erp.products.update',
        'erp.products.delete',
        'erp.products.restore',

        'erp.product_categories.view',
        'erp.product_categories.viewAny',
        'erp.product_categories.create',
        'erp.product_categories.update',
        'erp.product_categories.delete',
        'erp.product_categories.restore',

        'erp.inventory.view',
        'erp.inventory.viewAny',
        'erp.inventory.create',
        'erp.inventory.update',
        'erp.inventory.delete',
        'erp.inventory.restore',

        'erp.warehouses.view',
        'erp.warehouses.viewAny',
        'erp.warehouses.create',
        'erp.warehouses.update',
        'erp.warehouses.delete',
        'erp.warehouses.restore',

        'erp.currencies.view',
        'erp.currencies.viewAny',
        'erp.currencies.create',
        'erp.currencies.update',
        'erp.currencies.delete',
        'erp.currencies.restore',

        'erp.suppliers.view',
        'erp.suppliers.viewAny',
        'erp.suppliers.create',
        'erp.suppliers.update',
        'erp.suppliers.delete',
        'erp.suppliers.restore',

        'erp.sales.view',
        'erp.sales.viewAny',
        'erp.sales.create',
        'erp.sales.update',
        'erp.sales.delete',
        'erp.sales.restore',

        'erp.purchases.view',
        'erp.purchases.viewAny',
        'erp.purchases.create',
        'erp.purchases.update',
        'erp.purchases.delete',
        'erp.purchases.restore',

        'erp.accounting.accounts.view',
        'erp.accounting.accounts.viewAny',
        'erp.accounting.accounts.create',
        'erp.accounting.accounts.update',
        'erp.accounting.accounts.delete',
        'erp.accounting.accounts.restore',

        'erp.accounting.journals.view',
        'erp.accounting.journals.viewAny',
        'erp.accounting.journals.create',
        'erp.accounting.journals.update',
        'erp.accounting.journals.delete',
        'erp.accounting.journals.restore',

        'erp.orders.view',
        'erp.orders.viewAny',
        'erp.orders.create',
        'erp.orders.update',
        'erp.orders.delete',
        'erp.orders.restore',

        'erp.invoices.view',
        'erp.invoices.viewAny',
        'erp.invoices.create',
        'erp.invoices.update',
        'erp.invoices.delete',
        'erp.invoices.restore',

        'erp.recurring_invoices.view',
        'erp.recurring_invoices.viewAny',
        'erp.recurring_invoices.create',
        'erp.recurring_invoices.update',
        'erp.recurring_invoices.delete',
        'erp.recurring_invoices.restore',

        'erp.credit_notes.view',
        'erp.credit_notes.viewAny',
        'erp.credit_notes.create',
        'erp.credit_notes.update',
        'erp.credit_notes.delete',
        'erp.credit_notes.restore',

        'erp.expenses.view',
        'erp.expenses.viewAny',
        'erp.expenses.create',
        'erp.expenses.update',
        'erp.expenses.delete',
        'erp.expenses.restore',

        'erp.expense_categories.view',
        'erp.expense_categories.viewAny',
        'erp.expense_categories.create',
        'erp.expense_categories.update',
        'erp.expense_categories.delete',
        'erp.expense_categories.restore',

        'erp.reports.view',
        'erp.reports.viewAny',
        'erp.reports.create',
        'erp.reports.update',
        'erp.reports.delete',
        'erp.reports.restore',

        'erp.payment_gateways.view',
        'erp.payment_gateways.viewAny',
        'erp.payment_gateways.create',
        'erp.payment_gateways.update',
        'erp.payment_gateways.delete',
        'erp.payment_gateways.restore',

        'erp.projects.view',
        'erp.projects.viewAny',
        'erp.projects.create',
        'erp.projects.update',
        'erp.projects.delete',
        'erp.projects.restore',

        'erp.timesheets.view',
        'erp.timesheets.viewAny',
        'erp.timesheets.create',
        'erp.timesheets.update',
        'erp.timesheets.delete',
        'erp.timesheets.restore',

        'erp.fiscal-years.view',
        'erp.fiscal-years.viewAny',
        'erp.fiscal-years.create',
        'erp.fiscal-years.update',
        'erp.fiscal-years.delete',
        'erp.fiscal-years.restore',

        'erp.fiscal-periods.view',
        'erp.fiscal-periods.viewAny',
        'erp.fiscal-periods.create',
        'erp.fiscal-periods.update',
        'erp.fiscal-periods.delete',
        'erp.fiscal-periods.restore',

        // HR module permissions
        'hr.departments.view',
        'hr.departments.viewAny',
        'hr.departments.create',
        'hr.departments.update',
        'hr.departments.delete',
        'hr.departments.restore',

        'hr.positions.view',
        'hr.positions.viewAny',
        'hr.positions.create',
        'hr.positions.update',
        'hr.positions.delete',
        'hr.positions.restore',

        'hr.employees.view',
        'hr.employees.viewAny',
        'hr.employees.create',
        'hr.employees.update',
        'hr.employees.delete',
        'hr.employees.restore',

        'hr.contracts.view',
        'hr.contracts.viewAny',
        'hr.contracts.create',
        'hr.contracts.update',
        'hr.contracts.delete',
        'hr.contracts.restore',

        'hr.employment_contracts.view',
        'hr.employment_contracts.viewAny',
        'hr.employment_contracts.create',
        'hr.employment_contracts.update',
        'hr.employment_contracts.delete',
        'hr.employment_contracts.restore',

        'hr.attendances.view',
        'hr.attendances.viewAny',
        'hr.attendances.create',
        'hr.attendances.update',
        'hr.attendances.delete',
        'hr.attendances.restore',

        'hr.attendance_records.view',
        'hr.attendance_records.viewAny',
        'hr.attendance_records.create',
        'hr.attendance_records.update',
        'hr.attendance_records.delete',
        'hr.attendance_records.restore',

        'hr.leave_requests.view',
        'hr.leave_requests.viewAny',
        'hr.leave_requests.create',
        'hr.leave_requests.update',
        'hr.leave_requests.delete',
        'hr.leave_requests.restore',

        'hr.leave_types.view',
        'hr.leave_types.viewAny',
        'hr.leave_types.create',
        'hr.leave_types.update',
        'hr.leave_types.delete',
        'hr.leave_types.restore',

        'hr.leaves.view',
        'hr.leaves.viewAny',
        'hr.leaves.create',
        'hr.leaves.update',
        'hr.leaves.delete',
        'hr.leaves.restore',

        'hr.payrolls.view',
        'hr.payrolls.viewAny',
        'hr.payrolls.create',
        'hr.payrolls.update',
        'hr.payrolls.delete',
        'hr.payrolls.restore',

        'hr.payroll_runs.view',
        'hr.payroll_runs.viewAny',
        'hr.payroll_runs.create',
        'hr.payroll_runs.update',
        'hr.payroll_runs.delete',
        'hr.payroll_runs.restore',

        'hr.payroll_items.view',
        'hr.payroll_items.viewAny',
        'hr.payroll_items.create',
        'hr.payroll_items.update',
        'hr.payroll_items.delete',
        'hr.payroll_items.restore',

        'hr.recruitments.view',
        'hr.recruitments.viewAny',
        'hr.recruitments.create',
        'hr.recruitments.update',
        'hr.recruitments.delete',
        'hr.recruitments.restore',

        'hr.recruitment_openings.view',
        'hr.recruitment_openings.viewAny',
        'hr.recruitment_openings.create',
        'hr.recruitment_openings.update',
        'hr.recruitment_openings.delete',
        'hr.recruitment_openings.restore',

        'hr.performance_reviews.view',
        'hr.performance_reviews.viewAny',
        'hr.performance_reviews.create',
        'hr.performance_reviews.update',
        'hr.performance_reviews.delete',
        'hr.performance_reviews.restore',

        'hr.trainings.view',
        'hr.trainings.viewAny',
        'hr.trainings.create',
        'hr.trainings.update',
        'hr.trainings.delete',
        'hr.trainings.restore',

        'hr.training_courses.view',
        'hr.training_courses.viewAny',
        'hr.training_courses.create',
        'hr.training_courses.update',
        'hr.training_courses.delete',
        'hr.training_courses.restore',

        'hr.training_assignments.view',
        'hr.training_assignments.viewAny',
        'hr.training_assignments.create',
        'hr.training_assignments.update',
        'hr.training_assignments.delete',
        'hr.training_assignments.restore',

        'hr.training_enrollments.view',
        'hr.training_enrollments.viewAny',
        'hr.training_enrollments.create',
        'hr.training_enrollments.update',
        'hr.training_enrollments.delete',
        'hr.training_enrollments.restore',

        'hr.employee_documents.view',
        'hr.employee_documents.viewAny',
        'hr.employee_documents.create',
        'hr.employee_documents.update',
        'hr.employee_documents.delete',
        'hr.employee_documents.restore',

        'core.custom_dashboards.view',
        'core.custom_dashboards.viewAny',
        'core.custom_dashboards.create',
        'core.custom_dashboards.update',
        'core.custom_dashboards.delete',
        'core.custom_dashboards.restore',

        // E-Commerce module permissions
        'ecommerce.stores.view',
        'ecommerce.stores.viewAny',
        'ecommerce.stores.create',
        'ecommerce.stores.update',
        'ecommerce.stores.delete',

        'ecommerce.themes.view',
        'ecommerce.themes.viewAny',
        'ecommerce.themes.create',
        'ecommerce.themes.update',
        'ecommerce.themes.delete',

        'ecommerce.orders.view',
        'ecommerce.orders.viewAny',
        'ecommerce.orders.update',

        'ecommerce.pages.view',
        'ecommerce.pages.viewAny',
        'ecommerce.pages.create',
        'ecommerce.pages.update',
        'ecommerce.pages.delete',

        'ecommerce.content_blocks.view',
        'ecommerce.content_blocks.viewAny',
        'ecommerce.content_blocks.create',
        'ecommerce.content_blocks.update',
        'ecommerce.content_blocks.delete',
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission Groups
    |--------------------------------------------------------------------------
    |
    | Group permissions by module for easier management.
    |
    */

    'groups' => [
        'core' => [
            'users',
            'roles',
            'permissions',
            'teams',
            'custom_fields',
            'tenants',
            'custom_dashboards',
        ],
        'crm' => [
            'leads',
            'contacts',
            'deals',
            'accounts',
            'pipelines',
            'reports',
            'workflows',
            'import',
            'export',
            'email_accounts',
            'email_templates',
            'email_campaigns',
            'calendar_integrations',
            'lead_assignment_rules',
        ],
        'erp' => [
            'core',
            'products',
            'product_categories',
            'inventory',
            'warehouses',
            'currencies',
            'suppliers',
            'sales',
            'purchases',
            'accounting',
            'orders',
            'invoices',
            'recurring_invoices',
            'credit_notes',
            'expenses',
            'expense_categories',
            'reports',
            'payment_gateways',
            'projects',
            'timesheets',
            'fiscal-years',
            'fiscal-periods',
        ],
        'hr' => [
            'departments',
            'positions',
            'employees',
            'contracts',
            'employment_contracts',
            'attendances',
            'attendance_records',
            'leave_requests',
            'leave_types',
            'leaves',
            'payrolls',
            'payroll_runs',
            'payroll_items',
            'recruitments',
            'recruitment_openings',
            'performance_reviews',
            'trainings',
            'training_courses',
            'training_assignments',
            'training_enrollments',
            'employee_documents',
        ],
        'ecommerce' => [
            'stores',
            'themes',
            'orders',
            'pages',
            'content_blocks',
        ],
    ],
];

